### ISSUE TITLE
Forge not loading

### ISSUE THREAD

**Issue by over-charge** [killpowa/Twickt-Launcher#1516] opened 2023-01-18 01:21 UTC
- [ ] I searched the issue tracker for other issues covering my case
- [ ] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
_A clear and concise description of what the bug is._

**To Reproduce**

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Possible solutions**
_Some ideas of how you would solve this issue, if possible_

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Operating System:**
- OS: [e.g. Windows 10]
- Launcher Version: [e.g. v1.1.10]
- Java Version: [e.g. 8/16]
- Minecraft Version: [e.g. 1.16.5]
- Mod Loader: [e.g. Forge/Fabric]

**Additional context**
_Add any other context about the problem here._

**Comment by over-charge** [comment] 2023-01-18 01:26
Hi there, I am a steam deck user and everytime i try and download a modpack that includes opted out mods, it tries to open curse forge. After it tries to open curse forge, it tries to make sure that my connection is secure. However, it never loads, and if it does it immediately goes back to findimg a secure connection.

**Comment by Eskaan** [comment] 2023-01-18 05:42
Duplicate of #1513

**Closed as not planned** 2023-01-18 05:42 UTC
