### ISSUE TITLE
Keeps Trying to download Game files and gives this error code.Request failed with status code 403

### ISSUE THREAD

**Issue by ghost** [killpowa/Twickt-Launcher#1492] opened 2022-12-09 08:21 UTC
Error while downloading <https://cdn.gdlauncher.com/maven/org\apache\logging\log4j\log4j-slf4j2-impl\2.15.0\log4j-slf4j2-impl-2.15.0.jar | https://cdn.gdlauncher.com/maven/org/apache/logging/log4j/log4j-slf4j2-impl/2.15.0/log4j-slf4j2-impl-2.15.0.jar> to <C:\Users\omarr\AppData\Roaming\gdlauncher_next\datastore\libraries\org\apache\logging\log4j\log4j-slf4j2-impl\2.15.0\log4j-slf4j2-impl-2.15.0.jar> --> Request failed with status code 403
(anonymous) @ downloader.js:114
f @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:29
processTicksAndRejections @ node:internal/process/task_queues:96
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:29
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ downloader.js:59
(anonymous) @ downloader.js:37
f @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
downloader.js:114 Error while downloading <https://cdn.gdlauncher.com/maven/org\apache\logging\log4j\log4j-slf4j2-impl\2.15.0\log4j-slf4j2-impl-2.15.0.jar | https://cdn.gdlauncher.com/maven/org/apache/logging/log4j/log4j-slf4j2-impl/2.15.0/log4j-slf4j2-impl-2.15.0.jar> to <C:\Users\omarr\AppData\Roaming\gdlauncher_next\datastore\libraries\org\apache\logging\log4j\log4j-slf4j2-impl\2.15.0\log4j-slf4j2-impl-2.15.0.jar> --> Request failed with status code 403
(anonymous) @ downloader.js:114
f @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:29
processTicksAndRejections @ node:internal/process/task_queues:96
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:29
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ downloader.js:59
(anonymous) @ downloader.js:37
f @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
processTicksAndRejections @ node:internal/process/task_queues:96
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
actions.js:3126 Missing resource: C:\Users\omarr\AppData\Roaming\gdlauncher_next\datastore\libraries\org\apache\logging\log4j\log4j-slf4j2-impl\2.15.0\log4j-slf4j2-impl-2.15.0.jar

**Comment by Eskaan** [comment] 2022-12-09 08:36
Duplicate of #1491

**Closed as not planned by Eskaan** 2022-12-09 08:36 UTC
