### ISSUE TITLE
Quilt versions of mods show up in Forge instances, and if newer, are given priority over Forge versions when updating

### ISSUE THREAD

**Issue by taj1994** [killpowa/Twickt-Launcher#1416] opened 2022-07-27 23:32 UTC
**Describe the bug**
Quilt versions of mods show up in Forge instances, and if they're newer, are given priority over Forge versions when installing and updating. The specific mod I noticed this with is [GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib)

**To Reproduce**
1. Make Forge instance (I tested with both 1.18.2 and 1.19)
2. Go to "Add Mods" screen
3. Find mod that has both Forge and Quilt versions on the same mod page (GeckoLib for example)
4. Click on mod
5. Click on versions dropdown
6. See Forge and Quilt versions together

**Expected behavior**
To not see versions for an incompatible modloader

**Possible solutions**
Whatever was done to make Fabric versions not show up available for download in Forge instances and vice-versa

**Screenshots**
Mod showing update:
![image](https://user-images.githubusercontent.com/1844822/181388937-ad8a8936-014e-454f-acc0-ea891d521bd5.png)
Quilt versions showing up in version selection dropdown:
![image](https://user-images.githubusercontent.com/1844822/181388961-ea2db207-afed-4380-9b1c-fafd612b1d48.png)

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 17
- Minecraft Version: 1.18.2 and 1.19
- Mod Loader: Forge

**Comment by Eskaan** [comment] 2022-07-29 14:47
Duplicate of #1204

**Closed as not planned** 2022-07-29 14:47 UTC
