### ISSUE TITLE
Switching Version on FTB ModPacks doesn't visibly do anything

### ISSUE THREAD

**Issue by OreoDoublestuff** [killpowa/Twickt-Launcher#1385] opened 2022-06-27 01:28 UTC
Switching an FTB modpack from one version to another does not update anything in the modpack. The launcher displays the desired modpack version, but no mods have been updated. Different FTB modpacks do different things when the "Switch Version" process is watched in the console. Direwolf20 1.18.2 seems to try to patch Minecraft itself, while Stoneblock2 doesn't report much of anything in the console. I have attached a log of an attempt to switch versions for Direwolf. 

1. Download Direwolf20 1.18.2
2. Attempt to change the modpack version
3. It will report that it is downloading game files, then patching forge.
4. No mods will have been updated.

**Expected behavior**
Based on looking at a curseforge modpack, all the mods should get dumped out of the modpack folder, but nothing happens.

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 8
- Minecraft Version: 1.18.2
- Mod Loader: Forge
[DirewolfVersionChange.log](https://github.com/gorilla-devs/GDLauncher/files/8987998/DirewolfVersionChange.log)

**Comment by Eskaan** [comment] 2022-06-27 05:34
Duplicate of #1155

**Closed as not planned by Eskaan** 2022-06-27 05:34 UTC
