### ISSUE TITLE
can't download mods from curseforge

### ISSUE THREAD

**Issue by iDrunK65** [killpowa/Twickt-Launcher#1529] opened 2023-01-28 09:37 UTC
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
I can't download mods from curseforge, curseforge add cloudflare verification before show real page

**To Reproduce**
1. download modpack (ex: ragnamod VI)
2. After download, accept download from curseforge

**Expected behavior**
missing mods are downloaded

**Possible solutions**
increase time before refresh

**Screenshots**
![image](https://user-images.githubusercontent.com/25486774/215258981-2a122c38-0190-49df-bf1e-dcb9dd55539c.png)
![image](https://user-images.githubusercontent.com/25486774/215258955-c267ecdd-a2ec-4a56-a4c4-f91c7bb0d6e6.png)

**Operating System:**
- OS: Windows 10
- Launcher Version: v1.1.29
- Java Version: 16
- Minecraft Version: 1.16.5
- Mod Loader: Forge

**Comment by iDrunK65** [comment] 2023-01-28 09:41
sometime connection is secure but i'm not redirected on curseforge

**Comment by MadZeh** [comment] 2023-01-28 15:07
Can agree with that.

**Comment by Eskaan** [comment] 2023-01-28 15:11
> Can agree with that. 

Please, if you have the same issue don't make a comment but react to the message. A message should be made if the issue hasn't received an update for a very long time (1 month+) or if you have new information.

**Comment by Eskaan** [comment] 2023-01-28 15:12
Btw this is a duplicate of #1367

**Closed as not planned by Eskaan** 2023-01-28 15:12 UTC
