### ISSUE TITLE
Weird logging output in raw XML form

### ISSUE THREAD

**Issue by whitebear60** [killpowa/Twickt-Launcher#1465] opened 2022-10-20 15:32 UTC
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
The logs are displayed in raw XML (probably written for Minecraft launcher logger)

**To Reproduce**
1. Launch the Forge 1.12.2 instance
2. Open the console with the `>_` button at top-right corner
3. See the output

**Expected behavior**
Output to be shown in just plain text, without XML wrapping it

**Possible solutions**
Probably something's changed in `~/Library/Application Support/gdlauncher_next/datastore/assets/objects/bd/client-1.12.xml` or the launcher can't properly read it

**Screenshots**
<img width="800" alt="image" src="https://user-images.githubusercontent.com/42472132/196991989-28dfb2e8-8054-472d-933a-0b4553b434c2.png">

**Operating System:**
- OS: macOS
- Launcher Version: 1.1.29
- Java Version: 17 / 8
- Minecraft Version: 1.19 / 1.12.2 (tested both, encountered the same issue)
- Mod Loader: Vanilla 1.19 / Forge 1.12.2 (tested both, encountered the same issue)

**Comment by Eskaan** [comment] 2022-10-20 16:47
Duplicate of #1239

**Closed as not planned** 2022-10-20 16:47 UTC
