### ISSUE TITLE
Launcher not recognising prescence of Log4j2 file.

### ISSUE THREAD

**Issue by Bw3n15** [killpowa/Twickt-Launcher#1588] opened 2023-09-10 18:21 UTC
I have tried using this fix (the file was already present so I copied it over, deleted the original and made sure to rename correctly): https://github.com/gorilla-devs/GDLauncher/issues/1491#issuecomment-1343431347

The crash occurs when opening a world, it seems to load intially just fine, reaches a "Saving World" screen, it then hangs on the dirtblock background without the text for a few moment before crashing.

1. Create a new 1.19.1 Forge instance on the newest Forge version.
2. Install the worldedit mod.
3. Manually install Optifine (including BSL shaders)
4. Open a world (not sure if happens when creating as I am trying to port over a world I already have)

**Expected behavior**
The world loads and doesn't crash.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

- OS: Windows 11
- Launcher Version: I am unsure but it is whatever the newest version is as of the 9th November 2023.
- Java Version: I believe 17 but once again unsure.
- Minecraft Version: 1.19.1
- Mod Loader: Forge

I have included both crash reports, one from before I tried the previously mentioned fix and another from after.
[crash-2023-09-10_19.07.20-client.txt](https://github.com/gorilla-devs/GDLauncher/files/12569885/crash-2023-09-10_19.07.20-client.txt)
[crash-2023-09-10_19.11.25-client.txt](https://github.com/gorilla-devs/GDLauncher/files/12569886/crash-2023-09-10_19.11.25-client.txt)

**Comment by Eskaan** [comment] 2023-09-10 18:36
Duplicate of https://github.com/gorilla-devs/GDLauncher/issues/1195, it's all a result of the log4shell hotfix. Anyone trying to resolve this would be really appreciated.

**Closed as not planned** 2023-09-10 18:36 UTC

**Comment by Eskaan** [comment] 2023-09-10 18:38
Actually, it's more likely to not be an issue with Log4J and more with your mod combination (i.e. Optifine)

**Comment by Bw3n15** [comment] 2023-09-11 09:50
> Actually, it's more likely to not be an issue with Log4J and more with your mod combination (i.e. Optifine)

i doubt it. its only 2 mods that ive used together before and had no issues with

edit: this issue is resolved now. wasn't a mod combination, i was simply using an incompatible version of forge and optifine.
