### ISSUE TITLE
GDLauncher removes the instance after a failed download

### ISSUE THREAD

**Issue by noncom** [killpowa/Twickt-Launcher#1346] opened 2022-05-29 12:57 UTC
**Describe the bug**

As the result of download failing because of https://github.com/gorilla-devs/GDLauncher/issues/1342 GDLauncher removes the failed instance.
Related confirming claims:
- https://github.com/gorilla-devs/GDLauncher/issues/1342#issuecomment-1140366749
- https://github.com/gorilla-devs/GDLauncher/issues/1342#issuecomment-1133910377
- https://github.com/gorilla-devs/GDLauncher/issues/1342#issuecomment-1133925641

**To Reproduce**

1. Try to update an instance, like #1342 mentions it. Your instance gets deleted after the failure.

**Expected behavior**

GDLauncher should *never* delete an instance without an explicit and assured confirmation from the user.

Many people are just casual users who might not habitually think of needing to keep regular backups or to be in the need to backup their instance before doing a regular action that should not, and never had, lead to the instance deletion.

The launcher should never task the user with backing up their instance under a threat of accidental removal. If anything it should provide a nice way of making backups and keeping their registry.

**Possible solutions**

I think it's pretty much clear from the description -- just rethink how the process is handled by GDLauncher to exclude such mishappenings and maybe facilitate related GUI changes/additions.

Maybe do not remove the instance initially, keep a backup before later verifying the correctness of the new one. And provide the user with an option to restore from the backup.

**Screenshots**

There was an instance, and there it's gone.

**Operating System:**

- OS: Windows
- Version: 10
- Java Version: 8, 16, 17, depends
- Minecraft Version: 1.16.5, 1.18.2
- Mod Loader: Forge, Fabric

**Additional context**

Not sure if this issue has a chance to occur naturally or under any other curcumstances. I have a vague memory of an accidental and unannounced instance deletion by GDLauncher from quite a while ago, and that might have been also related to one of the many issues that CurseForge forges to curse us. But please just check and re-check all the program flow that handles instance management.

**Comment by ChaosieKinder** [comment] 2022-05-30 01:23
Came report this. No warning or anything. Glad I play on a server and didn't lose my world.

**Comment by Eskaan** [comment] 2022-05-30 08:58
Duplicate of #1288

**Closed as not planned** 2022-05-30 08:58 UTC
