### ISSUE TITLE
Create Live 3 crashes (and downloads horribly slow)

### ISSUE THREAD

**Issue by AntonioNoack** [killpowa/Twickt-Launcher#1542] opened 2023-02-07 16:45 UTC
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
![image](https://user-images.githubusercontent.com/20659579/217307039-0391dcc4-9649-4afc-83a2-29a7ab90e28b.png)
I would copy the crash report, but your UI doesn't allow it (kind of stupid)

Logs:
```
[17:39:38] [main/INFO]: ModLauncher running: args [--username, Miner952x, --version, 1.18.2, --gameDir, ..\..\instances\Create Live 3, --assetsDir, ..\..\datastore\assets, --assetIndex, 1.18, --uuid, 97bb00e35e014410891cfced29ffaff9, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.11, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, --width=854, --height=480]
[17:39:38] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 18.0.1.1 by Oracle Corporation
[17:39:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Antonio/AppData/Roaming/gdlauncher_next/datastore/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
```

**To Reproduce**
- Download "Create Life 3"
- Wait 500 years, until it is downloaded (why is it soo slow???)
- Start the instance, it crashes quickly, after ~4 seconds

**Expected behavior**
Starting instance

**Possible solutions**
Send the correct parameters, perhaps? 🤷‍♂️

**Screenshots**
See above.

**Operating System:**
- OS: Windows 10
- Launcher Version: v1.1.30
- Java Version: Jdk 18.0.1.1
- Minecraft Version: 1.18.2
- Mod Loader: Forge 40.1.11

**Additional context**
_Add any other context about the problem here._
The download took about an hour, on a 50Mbit/s line.
The server files (which crash for me as well 😕) from Curseforge were 200MB in size, and downloaded within roughly a minute.

**Comment by Eskaan** [comment] 2023-02-07 17:14
Duplicate of #1513

**Closed as not planned by Eskaan** 2023-02-07 17:14 UTC
