### ISSUE TITLE
Add Import mod/s button

### ISSUE THREAD

**Issue by DovydasTEDS** [killpowa/Twickt-Launcher#1461] opened 2022-10-10 17:25 UTC
So basically you could click add mods and either choose a file or folder to add the mods. There could also be a ui where you can browse your mods for a specific version, like the add mod button but for local mods.

**Comment by Eskaan** [comment] 2022-10-10 17:45
You can already drag mods into the mod manager. The other request is a duplicate of #1303.
Please use the given template next time.

**Closed as completed by Eskaan** 2022-10-10 17:45 UTC
