### ISSUE TITLE
Wrong modloader of mod installed (mostly problem with dependencies)

### ISSUE THREAD

**Issue by andreccr** [killpowa/Twickt-Launcher#1275] opened 2022-02-07 03:33 UTC
**Describe the bug**
When GeckoLib is installed automatically due to dependency handling, it seems to install the Fabric version by default even if the instance uses Forge. I am able to work around this by changing the version of GeckoLib installed manually.

**To Reproduce**
1. Create a new Forge instance for Minecraft 1.18.1 (I used Forge 39.0.66)
2. Right click > manage instance > Mods
3. Install a mod that depends on GeckoLib (behavior observed installing occultism-1.18.1-1.26.1)
4. Go back to the mod overview page that shows all the mods installed on the instance
5. Search "Fabric"
6. geckolib Fabric will be installed, along with Fabric API

**Expected behavior**
When the user installs a mod on a Forge instance, the system should install the Forge-compatible versions of dependencies automatically. In this instance, it should install geckolib-1.18.1-forge-3.0.11.

**Possible solutions**
It seems like the system already knows not to show Fabric versions of a mod in the version selection page. If it were to automatically pick the latest stable version of the mod from that list that would fix this problem.

**Screenshots**
Bug behavior (installed automatically by the dependency handling):
![Screenshot from 2022-02-06 21-20-08](https://user-images.githubusercontent.com/29599928/152719434-f64a5a71-013d-4a4b-a7a3-2bfffeb7c45e.png)
Only compatible versions are listed as options to switch to:
![Screenshot from 2022-02-06 21-19-49](https://user-images.githubusercontent.com/29599928/152719437-6dbb3037-402a-49e4-b074-b48594af621c.png)
After workaround/Expected Behavior:
![Screenshot from 2022-02-06 21-23-43](https://user-images.githubusercontent.com/29599928/152719600-2d65c6ab-c15d-40a7-9067-5ae8c448131a.png)

**Operating System:**
- OS: Linux
- Version: Manjaro + Gnome
- Java Version: OpenJDK 17.0.1 (also whichever version is installed automatically by GDLauncher)
- Minecraft Version: 1.18.1
- Mod Loader: Forge 39.0.66

**Additional context**

- When I go to the screen to change versions, it says "The installed version of this mod has been removed from CurseForge, so you will only be able to get it as part of legacy modpacks." Version of GeckoLib which is installed (geckolib-fabric-1.18-3.0.32)[https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3629662] does exist on CurseForge, but no longer appeared in the list of installable versions
- This problem also occurred when installing Ars Nouveau
- GeckoLib releases updates for several different Minecraft versions at the same time, and currently the main version on CurseForge is listed for Minecraft 1.12.2. The 1.18.1 Forge versions aren't listed as the "main version."

**Comment by andreccr** [comment] 2022-02-07 03:49
Duplicate of #1204

Apologies, I didn't search well enough for it before. Hopefully the extra detail helps though

**Comment by andreccr** [comment] 2022-02-07 03:51
Duplicate of #1204 (hopefully the extra detail is helpful)

**Comment by Peca21** [comment] 2022-02-10 18:50
Same here with "Feature NBT Deadlock Be Gone" and Repurposed Structures (Forge).  Downloading Repurposed Structures (Forge) downloads a fabric version of "Feature NBT Deadlock Be Gone."

**Comment by AshtakaOOf** [comment] 2022-02-11 02:00
this is a problem with the creator of the mod and he's not tagging the mod properly on curseforge that all we can't do anything about it

**Comment by Peca21** [comment] 2022-02-11 13:02
But "Feature NBT Deadlock Be Gone" fabric version is tagged with "Fabric", but still downloads to a forge instance

**Comment by AshtakaOOf** [comment] 2022-02-11 19:18
Blame the curseforge api

**Comment by Eskaan** [comment] 2022-06-20 18:14
Actually also a Duplicate
Man these are hard to find.
Duplicate of #1204

**Closed as not planned by Eskaan** 2022-06-20 18:14 UTC
Labels: Type: Bug
