### ISSUE TITLE
trying to install better minecraft plus v26.5 

### ISSUE THREAD

**Issue by zacharyhenry** [killpowa/Twickt-Launcher#1140] opened 2021-10-31 17:00 UTC
minecraft 1.16.5

bug stays on installing  forge installer

https://photos.app.goo.gl/ijNZVFNRxDbrD7UV7

**Comment by huantianad** [comment] 2021-10-31 17:07
Duplicate of #1086

**Comment by zacharyhenry** [comment] 2021-10-31 17:12
i had to change gdlauncher from stable release to beta for it to download

**Closed as completed** 2021-10-31 17:15 UTC
