### ISSUE TITLE
1.1.30 will not run on my OS, and GD is forcing me to update!

### ISSUE THREAD

**Issue by OctagonalHexy** [killpowa/Twickt-Launcher#1534] opened 2023-01-31 15:25 UTC
- [ yes ] I searched the issue tracker for other issues covering my case
- [ yes ] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
_Updating  to 1.1.30 automatically breaks my install because my glibc version is 2.31_

**To Reproduce**
1. Have a "stable" distro release with a glibc older than 2.33
2. start the 1.1.29 appimage to install/run gdlauncher.
3. Wait A little for it to finish downloading the 1.1.30 update.(you can see this happening if you start from the terminal)
4. close GDlauncher
5. Attempt to reopen gdlauncher.

**Expected behavior**
_When an update is incompatible with your OS, it should not automatically install it._

**Possible solutions**
_I would prefer if the devs could build the releases on older librarys like they did prior to 1.1.30, but if it turns that they need features of glibc 2.33+ like is expressed in this similar post about 1.1.1 https://github.com/gorilla-devs/GDLauncher/issues/851 then I would like _
to know if there is any way to prevent gdlauncher from auto updating to 1.1.30, especially because just compiling 1.1.30 on my own machine would ensure it brakes when 1.1.31 releases.

**Screenshots**
![image](https://user-images.githubusercontent.com/85406370/215797162-beb80b2d-0b5d-4f11-990b-59b0b8dea08f.png)

**Operating System:**
- OS: [Linux Mint 20.1 Cinnamon 4.8.6]
- Launcher Version: [1.1.30]
- Java Version: [I nuked java and every file related to it thinking it might solve this issue, so only the jre 8 and 17 version included with the install of GDLauncher 1.1.29]
- Minecraft Version: [N/A]
- Mod Loader: [N/A]

**Additional context**
_Is there A reason that there is no way to disable automatic updates in the settings?
Also I posted about this on the discord yesterday before I had done my last few hours of testing and research.
At the time I thought I had broken something by force closing the process because it seemed like it hung before putting A window on screen, I now know it hung because of the 1.1.30 update that released yesterday. (as seen in the screenshot.)_

Thanks in advance if you have any ideas!

**Comment by Mallchad** [comment] 2023-02-01 04:33
This looks like a duplicate of #1528

**Comment by Eskaan** [comment] 2023-02-01 09:43
It is. Don‘t know why I didn‘t close it earlier.

**Closed as not planned** 2023-02-01 09:43 UTC
