### ISSUE TITLE
Getting errors all the times when installing/updating modpacks from Curseforge

### ISSUE THREAD

**Issue by EricBuist** [killpowa/Twickt-Launcher#1523] opened 2023-01-21 21:34 UTC
- [X] I searched the issue tracker for other issues covering my case
- [X] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
Pretty much each time I install or update a modpack from Curseforge, I'm getting errors and the download fails. Either I'm getting a message about security checks and the download doesn't start, either I'm getting that my web browser is out of date but it is up to date and I cannot install a newer version without once again circumventing the package manager of my Linux distribution to force update a nightly. If this happens, the problem persists whatever I try, nothing is available by searching on Google besides recommendations to stop playing modded Minecraft because it is not worthwhile anymore (WHY was it worthwhile in the past and now it is not? Why are Youtubers still playing modded Minecraft while I won't be able?). Last time, things started to work again two weeks after and in the meanwhile, I had to give up on playing modded Minecraft on Linux, falling back to the overbloated Curse launcher that is "portable" because it works on Windows and Mac but not Linux.

**To Reproduce**
1. Create an instance for a Curseforge modpack such as All the Mods 7 to the Skies.
2. Let GDLauncher download Minecraft, Forge, and the mods it can.
3. Let GDLauncher try to download mods from Curseforge, by pressing Continue.
4. Observe the blocking error.

**Expected behavior**
GDLauncher should be able to download the mods.

**Possible solutions**
Curseforge being accessible from a regular Web browser, maybe GDLauncher could download using the default browser rather than its own builtin browser.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Operating System:**
- OS: Linux
- Launcher Version: [e.g. v1.1.10]
- Java Version: 17
- Minecraft Version: [1.18.2
- Mod Loader: [e.g. Forge/Fabric]

**Additional context**
_Add any other context about the problem here._

**Comment by disnaut** [comment] 2023-01-21 22:01
I'm having the same issue as above. It looks like there is a server side cookie that isn't set resulting in Error 400 AKA Bad request. It's been making my downloads slow, and I have gigabit internet. Wanted to give this a bump to see if the dev's see this.

Edit: This is what is coming from the debug console
![image](https://user-images.githubusercontent.com/10439244/213888882-aaac3ae4-dc1b-4199-a5ef-029e02d41168.png)

Edit 2:

await new Promise((resolve, reject) => {
      data.on('error', err => {
        console.error(err);
        reject(err);
      });

      data.on('end', () => {
        wStream.end();
        if (legacyPath) {
          wStreamLegacy.end();
        }
        resolve();
      });
    });
    return true;
  } catch (e) {  // <--- It is throwing an error from the promise. Might have something to do with how it is handled? I'm more familiar with angular than I am react, so I'm not as familiar with the framework.
    console.error(
      `Error while downloading <${url} | ${encodedUrl}> to <${fileName}> --> ${e.message}`
    );
    return false;
  }
};

Edit 3: From my research, this is a server side issue, not the client. So as of right now there is nothing that the dev's can do in order to fix this. It would have to be on curse forge's end for this.

**Comment by Eskaan** [comment] 2023-01-22 07:50
Duplicate of #1513

**Closed as not planned** 2023-01-22 07:50 UTC
