### ISSUE TITLE
Uncaught Fatal Exception when trying to launch instances with forge for MC versions 1.19 and above

### ISSUE THREAD

**Issue by tanchevk** [killpowa/Twickt-Launcher#1484] opened 2022-12-04 12:34 UTC
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
When attempting to launch an instance with the Forge modloader and MC versions 1.19 and above (tested on 1.19: 1.19.2) the launcher encounters a `ps stderr: The command line is too long.` with exit code 1

**To Reproduce**
1. Go to 'Add new instance'
2. Click on 'Vanilla'
3. Select 'Forge'
4. Scroll down to '1.19'
5. Select any version of the Forge modloader
6. Attempt to start instance
7. Observe uncaught fatal exception

**Expected behavior**
The instance starts

**Screenshots**
![image](https://user-images.githubusercontent.com/93494094/205490496-5b50844f-122a-4934-b1e9-c6aef0475589.png)
![image](https://user-images.githubusercontent.com/93494094/205490514-f96f8094-ec9a-473b-89da-4c6460d9b631.png)
![image](https://user-images.githubusercontent.com/93494094/205490525-9f3edaaf-24f7-4083-9cd3-b637b5c4d70c.png)
![image](https://user-images.githubusercontent.com/93494094/205490561-1497e782-aa54-4a42-bad3-413f4102c14c.png)
![image](https://user-images.githubusercontent.com/93494094/205490569-69cd68fe-c297-443a-8e48-740585779ab5.png)
![image](https://user-images.githubusercontent.com/93494094/205490715-28c46306-5eb9-4871-a3e1-ff7b96b04fd5.png)

**Operating System:**
- OS: Windows 11 Home 21H2
- Launcher Version: v1.1.25
- Java Version: 17 i think (don't remember which java ver 1.19 uses)
- Minecraft Version: 1.19
- Mod Loader: Forge 41.1.0 (tested on more)

**Additional context**
My GD launcher allocates 4GB of memory to MC Instances

**Comment by Eskaan** [comment] 2022-12-04 20:55
Most likely a duplicate of #1359
I recommend on which version your launcher is and check that with the actual latest release (v1.1.29 atm).

**Closed as not planned by Eskaan** 2022-12-04 20:55 UTC
