### ISSUE TITLE
Can't launch any 1.19 forge versions

### ISSUE THREAD

**Issue by AlieDupuis** [killpowa/Twickt-Launcher#1372] opened 2022-06-17 16:19 UTC
**Describe the bug**
When attempting to launch a forge instance (even with 0 mods) - get error code 1 - command line is too long. Tried with the latest 10 versions of Forge, still won't launch

**To Reproduce**
1. create new forge instance for minecraft 1.19
2. Do not add mods
3. Try to play

**Expected behavior**
Expected to be able to launch the instance, even without any mods in the instance

**Possible additional factors**
I also recently converted from Mojang to Microsoft login. Could pose issue. Was able to at least launch Minecraft in 1.16 with forge from previous versions.

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: [e.g. 8/16]
- Minecraft Version: 1.19
- Mod Loader: Forge

**Additional context**
Any and all combinations of active and inactive mods, new instances, etc still won't load an instance of 1.19 on my launcher. downloaded most recent release during testing as well.

**Comment by MacGallifrey** [comment] 2022-06-17 16:48
I can second this, the same thing happens for me, I get an "Uncaught Fatal Exception code 1: The Command Line Is To Long" error.

**Comment by Eskaan** [comment] 2022-06-17 22:47
Duplicate of #1359

**Closed as not planned** 2022-06-17 22:47 UTC
