### ISSUE TITLE
Structure Blocks Not Working

### ISSUE THREAD

**Issue by orian34** [killpowa/Twickt-Launcher#1595] opened 2023-11-10 13:14 UTC
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
It seems like using GD Launcher makes structure blocks in maps not work anymore. Switching to vanilla immediately makes them work again (by manually updating them)

**To Reproduce**
1. Play any map using structure blocks.
2. Structure blocks appears/supposed to trigger.
3. Nothing happens.

**Expected behavior**
Structure blocks working as intended.

**Operating System:**
- OS: [Windows 10]
- Launcher Version: [v1.1.30]
- Minecraft Version: [1.16.5,1.17.1] (doesn't seem to matter)

**Additional Info:**
It might be linked with structures using a specific folder that GD Launcher doesn't read. So the blocks try to open a dead link.

**Comment by Eskaan** [comment] 2023-11-13 14:48
Duplicate of #1132

**Closed as not planned** 2023-11-13 14:48 UTC
