### ISSUE TITLE
GDLauncher ignoring existance of 'Essentials' mod

### ISSUE THREAD

**Issue by BBoldt** [killpowa/Twickt-Launcher#1299] opened 2022-03-25 20:09 UTC
**Describe the bug**
When trying to install a modpack containing the mod "essentials", or trying to add it with the Instance manager, it seems as though the mod does not exist and it is skipped, and it does not show up at all in the instance manager as a mod that can be added.

I confirmed the file is included and added correctly in my pack's manifest.

**To Reproduce**
1. Install "Unclouded" modpack latest version (0.6) from curseforge, or go to instance manager and attempt to add mod, search for 'essentials', and the mod doesn't show up.

**Expected behavior**
Expected GDLauncher to download Essentials.

**Screenshot***
![](https://i.imgur.com/Pbjse99.png)

**Operating System:**
- OS: Windows
- Version: 11
- Java Version: [e.g. 8/16]
- Minecraft Version: 1.18.1
- Mod Loader: Forge

**Additional context**
The file in question that is invisible:
https://www.curseforge.com/minecraft/mc-mods/essentials/files/3616143

Relevant portion of my pack's manifest file:
`    {
      "projectID": 293752,
      "fileID": 3616143,
      "required": true
    }
`

**Comment by jarn123** [comment] 2022-04-30 13:36
I don't notice this issue in v1.1.22-beta. 1

**Comment by Eskaan** [comment] 2022-05-19 16:37
Duplicate of #1046 or #1272 (mentioned above).

**Closed as completed by Eskaan** 2022-05-19 16:37 UTC
