### ISSUE TITLE
"Chat Disabled Due to Missing Profile Public Key"

### ISSUE THREAD

**Issue by Minecrft-101** [killpowa/Twickt-Launcher#1600] opened 2023-12-20 14:45 UTC
I searched the issue tracker for other issues covering my case
This is a Launcher issue

**Describe the bug**
With the mods i have downloaded, i am unable to chat on my server. My friend has the exact same pack (I exported and sent jt to him) on curseforge, and he is able to use the chat fine.

**To Reproduce**
use GDLauncher with the mod list provided, and on some servers you cant chat.

**Expected behavior**
I can Chat

**Possible solutions**
I Have No idea what the issue is, so i have no possible solutions

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Operating System:**
- OS: Windows 11
- Launcher Version: v 1.1.30
- Minecraft Version: 1.20.2
- Mod Loader: fabric

**Additional context**
Here is the mod list, though i do not believe it has something to do with the issue
![image](https://github.com/gorilla-devs/GDLauncher/assets/67148908/d5c851d7-bd1b-465c-8644-d5210175f992)

**Comment by Eskaan** [comment] 2023-12-20 18:23
Duplicate of #1540

**Closed as not planned** 2023-12-20 18:23 UTC
