### ISSUE TITLE
Add support for mods marked as compatible with the major version in the mod browser

### ISSUE THREAD

**Issue by TechPro424** [killpowa/Twickt-Launcher#1436] opened 2022-08-15 15:29 UTC
**Is your feature request related to a problem? Please describe.**
In the mod browser, only mods compatible with the specific version of the instance (e.g: 1.19.2) are shown. But some mods are only marked as compatible with the major version (e.g: 1.19 or 1.19.x). However, in most cases, mods that are marked as compatible for the major version (e.g: 1.19 or 1.19.x) work on the specific versions as well.

**Describe the solution you'd like**
In the mod browser, instead of showing mods only compatible with that specific version (e.g: 1.19.2), also show mods that are compatible with the major version (e.g: 1.19.x or 1.19)

**Comment by Eskaan** [comment] 2022-08-15 18:43
Duplicate of #1303

**Closed as not planned** 2022-08-15 18:44 UTC
