### ISSUE TITLE
Launcher download stuck when download source partially unavailable

### ISSUE THREAD

**Issue by Supermarcel10** [killpowa/Twickt-Launcher#1527] opened 2023-01-26 23:32 UTC
- [X] I searched the issue tracker for other issues covering my case
- [X] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
Any selected game version will not work when attempting to download through the launcher. I believe this to be an issue with Mojang/Microsoft servers where the files are partially unavailable. The download hangs or continues very slowly, where instead it could raise an error that the files are unobtainable.

**To Reproduce**
1. Open launcher.
2. Click on '+'.
3. Select any Vanilla release.
4. Give it a name.
5. Launcher will get stuck downloading.

**Expected behavior**
Expected for the launcher to download the selected version. Took about 20-30 mins to download 5%.
Normal minecraft launcher downloads about 60-70% within 2-3 seconds, raises an error that files could not be downloaded (possibly due to a faulty mirror or server from Mojang/Microsoft).

**Possible solutions**
Possibly look for issues with getting stuck obtaining the files. Raise an error or information that file could not be obtained or a timeout limit is exceeded.

**Screenshots**
![image](https://user-images.githubusercontent.com/47798787/214972907-43242eff-1fb7-44f4-9fcf-6d34b63c7ec7.png)

**Operating System:**
- OS: Windows 10 20H2 19042.631
- Launcher Version: v1.1.29
- Java Version: 17.01 2021-10-19
- Minecraft Version: 1.19.3
- Mod Loader: Vanilla

**Additional context**
N/A

**Comment by FairyKairi** [comment] 2023-01-27 02:51
This is also an issue with any new modpacks, no matter the version.  I will make a separate post, if needed.  Importing ZIPs also do not work.  I have been trying to download ATMS Spellbound for two weeks now.

**Comment by Supermarcel10** [comment] 2023-01-27 03:16
Looks like it may be a combination of multiple bugs:
- Importing ZIPs not working,
- Issue with successful downloads.

A mitigation should be done in the first place to prevent download issues. I.e. If a connection to a server is dropped, or a file fails to download, the launcher should continue the attempt for a timeout period, before throwing an error should be displayed rather. I'm not saying that's how it is in the source code, since I haven't looked into it - but that's what I would expect. (This might not be the case of my bug, but could be a high probability, since Mojang servers were degraded at the time of post, and it's possible the launcher could not establish connection/drop out).

I assume all of these bugs could be caused by a single very specific bug, like maybe handling of the files - since then it would be the same for ZIPs or online files.

**Comment by Eskaan** [comment] 2023-01-27 05:44
Duplicate of #1513

**Closed as not planned by Eskaan** 2023-01-27 05:44 UTC
