### ISSUE TITLE
Searching for a mod that is installed then clearing the text doesn't work

### ISSUE THREAD

**Issue by Eatham532** [killpowa/Twickt-Launcher#1374] opened 2022-06-18 01:52 UTC
**Describe the bug**
When searching for installed mods, the clear button doesn't work

**To Reproduce**
1. Under instance manager --> Mods search for a mod that is installed
2. Press the *x* button to clear the text
3. Doesn't work

**Expected behavior**
The text is ment to clear

**Possible solutions**
Nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/78714349/174417833-e5312d09-4d81-427c-bbdf-a6594274434f.png)

**Operating System:**
- OS: Windows
- Version: v 1.1.25

**Additional context**
Nothing

**Comment by Eskaan** [comment] 2022-06-18 08:50
Duplicate of #1366

**Closed as not planned by Eskaan** 2022-06-18 08:50 UTC
