### ISSUE TITLE
Minecraft 1.19.3 game files couldnt be downloaded http not working

### ISSUE THREAD

**Issue by MagnetarOps** [killpowa/Twickt-Launcher#1538] opened 2023-02-04 12:51 UTC
By Downloading a New Instance of a Minecraft 1.19 Modpack it keeps retrying to Download the Minecraft game Files from resources.download.minecraft.net over http it seems like minecraft switched to https. Because when trying to use the http Url in browser i get an error. By switching to https I could download the file in browser. 

**To Reproduce**
Download a new instance of Astropilis (Modpack CurseForge)
**Expected behavior**
Downloading and finishing Download. After Klick on Play and not restarting download. 

**Possible solutions**
switching from http to https

**Screenshots**
Here errors as text becouse Couldn't upload Screenshot. 
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/c2/c2edf0c… | http://resources.download.minecraft.net/c2/c2edf0c…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/c2/c2edf0c61913e0351087ab0beb002820b0bdfa52> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/0c/0c1e15b… | http://resources.download.minecraft.net/0c/0c1e15b…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/0c/0c1e15b0c2e32d698fbdafe47f09c90976126542> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/60/6017b34… | http://resources.download.minecraft.net/60/6017b34…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/60/6017b341f38ee9dae4bc9a320af865e083b1caaa> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/c2/c2edf0c… | http://resources.download.minecraft.net/c2/c2edf0c…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/c2/c2edf0c61913e0351087ab0beb002820b0bdfa52> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/5c/5c26e97… | http://resources.download.minecraft.net/5c/5c26e97…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/5c/5c26e976b740537457aafe2b06483b609c5c9217> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/0c/0c1e15b… | http://resources.download.minecraft.net/0c/0c1e15b…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/0c/0c1e15b0c2e32d698fbdafe47f09c90976126542> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/60/6017b34… | http://resources.download.minecraft.net/60/6017b34…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/60/6017b341f38ee9dae4bc9a320af865e083b1caaa> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/79/79d0a37… | http://resources.download.minecraft.net/79/79d0a37…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/79/79d0a37f47ec935fc2dbc54752bbee41a890d8e1> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/85/85e031c… | http://resources.download.minecraft.net/85/85e031c…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/85/85e031c8e1343cd0a331394821cb168080ab652b> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/5c/5c26e97… | http://resources.download.minecraft.net/5c/5c26e97…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/5c/5c26e976b740537457aafe2b06483b609c5c9217> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/79/79d0a37… | http://resources.download.minecraft.net/79/79d0a37…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/79/79d0a37f47ec935fc2dbc54752bbee41a890d8e1> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/85/85e031c… | http://resources.download.minecraft.net/85/85e031c…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/85/85e031c8e1343cd0a331394821cb168080ab652b> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/5c/5c26e97… | http://resources.download.minecraft.net/5c/5c26e97…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/5c/5c26e976b740537457aafe2b06483b609c5c9217> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/a1/a1daff5… | http://resources.download.minecraft.net/a1/a1daff5…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/a1/a1daff5daa55f870c29becece97fc88e3da0b18e> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/79/79d0a37… | http://resources.download.minecraft.net/79/79d0a37…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/79/79d0a37f47ec935fc2dbc54752bbee41a890d8e1> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/85/85e031c… | http://resources.download.minecraft.net/85/85e031c…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/85/85e031c8e1343cd0a331394821cb168080ab652b> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/a1/a1daff5… | http://resources.download.minecraft.net/a1/a1daff5…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/a1/a1daff5daa55f870c29becece97fc88e3da0b18e> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/8e/8e1b990… | http://resources.download.minecraft.net/8e/8e1b990…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/8e/8e1b990f1904fee612f096217e4c1f5e070da4eb> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/bf/bfe463d… | http://resources.download.minecraft.net/bf/bfe463d…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/bf/bfe463d86f6dd29972a8b144d327ca0ac893a3ac> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/a1/a1daff5… | http://resources.download.minecraft.net/a1/a1daff5…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/a1/a1daff5daa55f870c29becece97fc88e3da0b18e> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/18/1845bd4… | http://resources.download.minecraft.net/18/1845bd4…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/18/1845bd4c5ab4480491f9fe24494db55d417c76ba> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/8e/8e1b990… | http://resources.download.minecraft.net/8e/8e1b990…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/8e/8e1b990f1904fee612f096217e4c1f5e070da4eb> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/bf/bfe463d… | http://resources.download.minecraft.net/bf/bfe463d…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/bf/bfe463d86f6dd29972a8b144d327ca0ac893a3ac> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/18/1845bd4… | http://resources.download.minecraft.net/18/1845bd4…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/18/1845bd4c5ab4480491f9fe24494db55d417c76ba> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/8e/8e1b990… | http://resources.download.minecraft.net/8e/8e1b990…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/8e/8e1b990f1904fee612f096217e4c1f5e070da4eb> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/bf/bfe463d… | http://resources.download.minecraft.net/bf/bfe463d…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/bf/bfe463d86f6dd29972a8b144d327ca0ac893a3ac> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/9b/9b5c92c… | http://resources.download.minecraft.net/9b/9b5c92c…> to </home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets/objects/9b/9b5c92c9b0ca3b03f80f7efbd2c46213321efa36> --> Request failed with status code 400
downloader.js:114 Error while downloading <http://resources.download.minecraft.net/43/430b0fd… 

**Operating System:**
- OS: Manjaro
- Launcher Version: 1.1.29 (Flatpack)
- Minecraft Version: 1.19.3
- Mod Loader: Forge

**Comment by Eskaan** [comment] 2023-02-04 14:08
Duplicate of #1513

**Closed as not planned by Eskaan** 2023-02-04 14:08 UTC
