### ISSUE TITLE
Fabric instances download wrong dependencies 

### ISSUE THREAD

**Issue by FlynnLies** [killpowa/Twickt-Launcher#1546] opened 2023-02-19 16:06 UTC
**Describe the bug**
On fabric instances, when a mod downloads it's dependencies automatically and there are i.e. also forge versions available it downloads those. 

**To Reproduce**
1. Create new instance and choose vanilla->fabric->Releases->1.19.2->0.14.14 (i.e.)
2. After downloading, right-click on the instance->manage and navigate to mods. 
3. Then click on "Add mod", choose a mod with a dependency such as "Enchantment Descriptions" (Requires "Bookshelf") and download the latest version.
4. Go back to the installed mods and look for "Bookshelf". The installed version will be Bookshelf-Forge-1.19.2-x. Clicking on it GDLauncher will say "The installed version of this mod has been removed from CurseForge, ..." which is also incorrect.

**Expected behavior**
Bookshelf has Fabric versions such as Bookshelf-Fabric-1.19.2-x, so that should be downloaded instead.

**Possible solutions**
Do the same check you do for when selecting mod versions manually.

**Screenshots**
Doesn't apply.

**Operating System:**
- OS: Windows 10
- Launcher Version: v1.1.30
- Java Version: any (17)
- Minecraft Version: any
- Mod Loader: Fabric

**Additional context**
None.

**Comment by Eskaan** [comment] 2023-02-21 17:52
Duplicate of #1204

**Closed as not planned by Eskaan** 2023-02-21 17:52 UTC
