### ISSUE TITLE
Updated a modpack but game shows previous version

### ISSUE THREAD

**Issue by DeciTM** [killpowa/Twickt-Launcher#1380] opened 2022-06-23 13:33 UTC
**Describe the bug**
I updated the DW20 modpack to 1.6.0 from 1.5.1 but the in-game version isn't updated

**To Reproduce**
I updated via the steps provided in the FAQ

**Expected behavior**
In-game version should display 1.6.0

**Possible solutions**
Is there a file indicating version that didn't get updated/changed?

**Screenshots**
![lAa8KYe](https://user-images.githubusercontent.com/31772276/175311413-629e3a8b-29e4-4f05-8a59-1c05da18c232.png)
![s1QGarn](https://user-images.githubusercontent.com/31772276/175311468-2dcba99a-7296-42f7-9bdf-89f35f897e1e.png)

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 17
- Minecraft Version: 1.18.2
- Mod Loader: Forge

**Comment by Eskaan** [comment] 2022-06-23 15:17
Duplicate of #1155

**Closed as not planned by Eskaan** 2022-06-23 15:17 UTC
