### ISSUE TITLE
Extreme Slowness

### ISSUE THREAD

**Issue by murilorodelli** [killpowa/Twickt-Launcher#1549] opened 2023-02-23 01:11 UTC
I'm experiencing an extreme slowness even when creating an empty pack. The same operations in prism launcher is much faster for comparison.

**Comment by Eskaan** [comment] 2023-02-25 16:57
Most likely a duplicate of #1513. Not enough information provided to narrow down the issue, please supply information from the issue form if needed.

**Closed as not planned by Eskaan** 2023-02-25 16:57 UTC
