### ISSUE TITLE
Creating now mod pack stuck at 0%

### ISSUE THREAD

**Issue by TheSexyYeti** [killpowa/Twickt-Launcher#1139] opened 2021-10-31 03:11 UTC
I'm having an issue where I'm trying to create a new mod pack. But it get's to the part where is starts downloading the forge files. And it get's stuck at 0% .

**Comment by huantianad** [comment] 2021-10-31 03:12
Duplicate of #1086

**Closed as completed** 2021-10-31 08:50 UTC
