### ISSUE TITLE
Java Memory slider does not display correctly

### ISSUE THREAD

**Issue by LeFauxMatt** [killpowa/Twickt-Launcher#1178] opened 2021-11-24 06:13 UTC
**Describe the bug**
On version 1.1.16-beta.1 the Java Memory slider does not display correctly.

**To Reproduce**
1. Go to GDLauncher
2. Click on Settings > Java
3. Scroll down to Java Memory

**Expected behavior**
It should be possible to see 1, 2, 4, 8, 16, and 32GB memory options without overlapping text.

**Possible solutions**
32768MB should be further to the right so that 1, 2, and 4GB can be displayed without overlapping text.

**Screenshots**
![image](https://user-images.githubusercontent.com/3005344/143184270-d6845b39-56c9-46f4-a0d5-59def5019518.png)

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 17
- Minecraft Version: Not applicable
- Mod Loader: Not applicable

**Additional context**
Pretty self-explanatory.

**Comment by joye-ramone** [comment] 2021-12-12 13:09
Same issue. Difficult to understand what value is currently selected.

**Comment by huantianad** [comment] 2021-12-21 18:15
Duplicate of #1090.

**Closed as completed** 2021-12-28 19:41 UTC
