### ISSUE TITLE
Ko-fi link donation is broken

### ISSUE THREAD

**Issue by bentalexanderhaase** [killpowa/Twickt-Launcher#1562] opened 2023-04-14 19:35 UTC
- [x] I searched the issue tracker for other issues covering my case
- [ ] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
_A clear and concise description of what the bug is._

Clicking on the Ko-fi button does not work and redirects you to Ko-fi's main page

**To Reproduce**
1. Go to [https://github.com/gorilla-devs/GDLauncher](https://github.com/gorilla-devs/GDLauncher)
3. Click on 'ko-fi.com/gdlauncher'
4. Scroll down to -
5. See error

**Expected behavior**
_A clear and concise description of what you expected to happen._
Ko-fi page for GDLauncher loads

**Possible solutions**
_Some ideas of how you would solve this issue, if possible_
Fix link

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Clicking this link / link on your main website:

![image](https://user-images.githubusercontent.com/5788982/232138706-c2dea8c9-07b9-4b55-8667-996f61e52f83.png)

Leads to the main page of Ko-fi:

![image](https://user-images.githubusercontent.com/5788982/232139277-8c81c855-e61d-4371-b69c-911254013ce4.png)

**Operating System:**
- OS: Windows / Linux
- Launcher Version: -
- Java Version: -
- Minecraft Version: -
- Mod Loader: -

**Additional context**
_Add any other context about the problem here._

**Comment by Eskaan** [comment] 2023-04-15 07:16
Duplicate of #1544

**Closed as not planned by Eskaan** 2023-04-15 07:16 UTC
