### ISSUE TITLE
Still unable to download curseforge modpacks

### ISSUE THREAD

**Issue by CanBoy67** [killpowa/Twickt-Launcher#1370] opened 2022-06-16 20:22 UTC
**Describe the bug**
When I go to install a curseforge modpack or a custom modpack zip the launcher crashes at 89% 
**To Reproduce**
1. Download Modpack/Import Custom Modpack
2. Wait until 89% complete downloading mods
3. Program Crashes

**Expected behavior**
Modpack to download mods completely

**Possible solutions**
No idea

**Screenshots**
![Screenshot 2022-06-16 162026](https://user-images.githubusercontent.com/186977/174157052-7fc71bb6-1d47-4d3e-8310-58d060497a94.png)

**Operating System:**
- OS: Windows
- Version: 11
- Java Version: 8/17
- Minecraft Version: 1.12.2/1.16.5/1.18.2
- Mod Loader: Forge

**Additional context**

**Comment by lrb5305** [comment] 2022-06-16 20:59
The CurseForge tab isn't even loading for me again

**Comment by Ladvace** [comment] 2022-06-18 10:31
do you have the latest version of gd?

**Comment by Jonius7** [comment] 2022-06-18 10:42
I get "An error occurred while loading the modpacks list...
<img width="669" alt="Modpacks List Loading Error" src="https://user-images.githubusercontent.com/1049415/174434156-7fe6897f-91b3-4973-9d41-68970461923f.PNG">
"

**Comment by lrb5305** [comment] 2022-06-18 17:32
Mnaually updated following advice i found in the discord to download from
the websote and re-install. Working now

**Comment by Eskaan** [comment] 2022-06-18 19:03
@CanBoy67 which version of the Launcher do you have (Settings/General at the bottom?) Does manual upgrading fix it for you?

**Comment by CanBoy67** [comment] 2022-06-26 14:41
just updated to 1.1.25 and the problem still presists

**Comment by CanBoy67** [comment] 2022-06-26 14:50
just updated to 1.1.25 and manual update didn't fix it

**Comment by Eskaan** [comment] 2022-06-26 16:27
Could you open the console and provide the logs please? (>_ at the top)

**Comment by CanBoy67** [comment] 2022-06-26 18:34
Does this help
![Screenshot 2022-06-26 143338](https://user-images.githubusercontent.com/186977/175829054-179e1adc-8b8c-4ce2-90b6-4fb0f95a89db.png)

**Comment by Yoosk** [comment] 2022-06-26 18:46
its fixed in developer build
https://github.com/gorilla-devs/GDLauncher/actions/runs/2564823919
or
https://nightly.link/gorilla-devs/GDLauncher/actions/runs/2564823919

**Comment by Eskaan** [comment] 2022-06-26 19:17
I am tempted to mark it as duplicate of #1359. Will leave it here for now as the fix is on the way.

**Comment by Ladvace** [comment] 2022-06-28 17:03
do you still get this error?

**Comment by CanBoy67** [comment] 2022-06-29 14:30
If you mean me using the dev version has fixed the issue

**Closed as completed** 2022-07-04 18:59 UTC
Labels: Type: Bug, Status: Awaiting Feedback
