### ISSUE TITLE
Launcher not launching in Debian

### ISSUE THREAD

**Issue by drifted04** [killpowa/Twickt-Launcher#1571] opened 2023-06-09 04:57 UTC
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
The launcher does not launch, when running in terminal I get the following error:
`A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot open /opt/GDLauncher/resources/app.asar/build/native/nsfw.node: Error: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.33' not found (required by /tmp/.org.chromium.Chromium.oZc3ho)
    at Object.<anonymous> (/opt/GDLauncher/resources/app.asar/build/electron.js:2:2736106)
    at ./public/native/nsfw.node (/opt/GDLauncher/resources/app.asar/build/electron.js:2:2736144)
    at i (/opt/GDLauncher/resources/app.asar/build/electron.js:2:124)
    at ./public/nsfw.js (/opt/GDLauncher/resources/app.asar/build/electron.js:2:2736280)
    at i (/opt/GDLauncher/resources/app.asar/build/electron.js:2:124)
    at ./public/electron.js (/opt/GDLauncher/resources/app.asar/build/electron.js:2:2723428)
    at i (/opt/GDLauncher/resources/app.asar/build/electron.js:2:124)
    at module.exports../node_modules/base64url/dist/base64url.js (/opt/GDLauncher/resources/app.asar/build/electron.js:2:923)
    at Object.<anonymous> (/opt/GDLauncher/resources/app.asar/build/electron.js:2:953)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)`

**To Reproduce**
1. Open GDlauncher
2. See error

**Expected behavior**
The launcher to launch as expected

**Possible solutions**
No idea

**Screenshots**
None

**Operating System:**
- OS: Debian 11
- Launcher Version: v1.1.30 .deb version
- Java Version: JDK 17.0.6
- Minecraft Version: NA
- Mod Loader: NA

**Additional context**
I have tried reinstalling the launcher several times.

**Comment by Eskaan** [comment] 2023-06-11 19:27
Duplicate of #1528

**Closed as not planned by Eskaan** 2023-06-11 19:27 UTC
