### ISSUE TITLE
Custom User-Made Themes

### ISSUE THREAD

**Issue by GhostIsBeHere** [killpowa/Twickt-Launcher#1312] opened 2022-04-21 17:30 UTC
**Is your feature request related to a problem? Please describe.**
Make a way for users to create UI themes

**Describe the solution you'd like**
Make a setting that lets users create/import "themes"
This would let users change the UI colors, logos, fonts, and add a picture for the backdrop. Recommended to implemet using CSS stylesheets.

**Describe alternatives you've considered**
Make a custom format that limits the things that can be changed. While full CSS changing would be ideal, just changing colors and adding a picture for the backdrop would work as well.

**Comment by Eskaan** [comment] 2022-05-17 12:16
Duplicate of either #339 or #409

**Closed as completed by Eskaan** 2022-05-17 12:16 UTC
