### ISSUE TITLE
Java Memory Layout Issue

### ISSUE THREAD

**Issue by SamHoque** [killpowa/Twickt-Launcher#1217] opened 2021-12-20 22:08 UTC
**Describe the bug**
When you have more than 16GB of Ram, the memory slider layout is overlapped and is hard to read.

![image](https://user-images.githubusercontent.com/30783651/146839113-0a24fb3d-73f6-4911-a515-0bb0cff50a57.png)

**Comment by huantianad** [comment] 2021-12-21 18:15
Duplicate of #1090.

**Closed as completed** 2021-12-25 10:11 UTC
