### ISSUE TITLE
Forge 1.19 instance doesen't start

### ISSUE THREAD

**Issue by UltraHamster64** [killpowa/Twickt-Launcher#1396] opened 2022-07-09 17:28 UTC
Description:
Freshly downloaded instance of any version on Forge 1.19 doesen't start, exits with "Uncaught fatal error Code 1"

GDLauncher actually doesen't download any files other than config with fresh instance of Forge 1.19 (see 3rd screenshot)

To reproduce:
1. Download a fresh version of Forge 1.19 (any modloader version)
2. Start instance

Expected behavior:
Instance starting

Screenshots
[![image.png](https://i.postimg.cc/15vjqN6x/image.png)](https://postimg.cc/kBtsrGfw)
[![image.png](https://i.postimg.cc/ZnTw9T5K/image.png)](https://postimg.cc/MMF7NJBh)
[![image.png](https://i.postimg.cc/MXJK0rgT/image.png)](https://postimg.cc/V048m4fQ)

Operating System:
- OS: Windows 10
- Java Version: tested on 17.0.1+12 (gdlauncher pack-in) and 17.0.1 globaly installed
- Minecraft Version: 1.19
- Mod Loader: Forge (any version)

**Comment by Dex-zabeth** [comment] 2022-07-10 13:04
I have a similar problem no matter what I do any gd launcher attempt to. Start a gorge 1.19 fails.  But I getting an error saying command line is to long

**Comment by Eskaan** [comment] 2022-07-11 05:49
Duplicate of #1359

**Closed as not planned** 2022-07-11 05:49 UTC
