### ISSUE TITLE
Output Log Not Working / Public Chat Disabled

### ISSUE THREAD

**Issue by orian34** [killpowa/Twickt-Launcher#1614] opened 2024-05-22 19:41 UTC
I noticed at some point, the valuable output log for minecraft just stopped working when using GDLauncher. Using vanilla works, but when using GD instances it just sends this error and never goes beyond. (And on a sidenote, it seems like I'm unable to send chat messages in servers, I wonder if it's linked.)

![image](https://github.com/gorilla-devs/GDLauncher/assets/12663654/15961535-c78a-4879-8158-0d4f6f959399)

**Comment by Eskaan** [comment] 2024-05-25 09:14
Duplicate of #1195.
See also: #1540 (probably related)
Also, have you ever heard about [pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)? I'm usually not very helpful if you don't fill out the form with the information I need. There would have been two very important check-marks for you right at the top.

**Comment by orian34** [comment] 2024-05-25 11:26
Ah, I see yeah, I had seen some of those but since I didn't understand the technical details I didn't think it was the same cause.
Seems like the issues are currently unresolved then, good to know.

**Closed as not planned** 2024-05-26 08:03 UTC
