### ISSUE TITLE
Download speed unreasably slow suddenly

### ISSUE THREAD

**Issue by nijahplays** [killpowa/Twickt-Launcher#1524] opened 2023-01-24 04:20 UTC
- [ x] I searched the issue tracker for other issues covering my case
- [ x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
Downloading game files is really slow

**To Reproduce**
1. Use Vanilla OS
2. Use appimage for GDLauncher
3. download a curseforge modpack
4. Downloads incredibly slow

**Expected behavior**
Download at a reasonable speed, which it was a few versions ago.

**Operating System:**
- OS: Vanilla OS (Ubuntu 22.10 based)
- Launcher Version: Current
- Java Version: Default
- Minecraft Version: 1.19.2
- Mod Loader: Fabric

**Comment by Eskaan** [comment] 2023-01-24 06:47
Duplicate of #1513

**Closed as not planned by Eskaan** 2023-01-24 06:47 UTC
