### ISSUE TITLE
[1.19] can't launch a Forge Instance

### ISSUE THREAD

**Issue by Bass2style** [killpowa/Twickt-Launcher#1377] opened 2022-06-20 02:38 UTC
**Describe the bug**
i can't run any recent 1.19 Forge instances (not tested with older Forge versions) because the "command is too long"
edit : tested with Forge 41.0.1, and it's also happening on this version.

**To Reproduce**
1. Create a 1.19 Forge instance
2. Launch it, even without mods
3. you get an error screen

**Expected behavior**
Not having an error when launching my instance. lul

**Possible solutions**
the command seems to load all libraries or something in the command with the "-cp" argument, avoiding this should drasticly reduce the command size.

**Screenshots**
the whole yellow area is an unique argment to load libs and dependencies. 

![args](https://user-images.githubusercontent.com/29619787/174515482-eb0cbc32-ce19-4dfe-9922-e257ca6c6d82.png)

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 17.0.1
- Minecraft Version: 1.19
- Mod Loader: Forge

**Additional context**
the console output : https://gist.github.com/Bass2style/d06498ce5bc5b114e0f8ce132c35d1a6 (already available on the screenshot.)

**Comment by Eskaan** [comment] 2022-06-20 07:22
Duplicate of #1359

**Closed as not planned by Eskaan** 2022-06-20 07:22 UTC
