### ISSUE TITLE
How do you manually set the size of the GDLauncher

### ISSUE THREAD

**Issue by menoobslayer** [killpowa/Twickt-Launcher#1553] opened 2023-03-06 16:57 UTC
Dumb launcher doesn't seem to know how to recognize a 1920x1080p display.
So the default size when it is 'windowed' is MUCH larger then the size it is when set to fullscreen

Making it unusable unless it is in fullscreen.

This shouldn't be a complicated thing to fix.
Please tell me where the resolution parameters are in the file directory so that I can manually set it to the proper size as it should have set by default. attached is a screenshot of how useless the default sizing for this program is.
It shouldn't be necessary to understand my issue though, so please just tell me where the resolution data is.
![gdlauncherisbroken](https://user-images.githubusercontent.com/37314622/223177872-36b13d9a-19ed-4972-90e8-ec982253abc0.png)

**Comment by Eskaan** [comment] 2023-03-07 06:32
# This is a moderation warning
Against @menoobslayer
### Main reasons

First of all this is a **duplicate of [your own issue](https://github.com/gorilla-devs/GDLauncher/issues/1545)** from less than a month ago. That alone is a reason to close this issue. You can always ask for additional help or information on this issue there.

Secondly you (again) **did not use the issue form** providing helpful information about your system. This issue form is designed to guide you through creating a ticket on the tracker containing most of the necessary data we need to diagnose and properly address your issue.

And third this is **inappropriate language**. Although this is a rather mild insult, it's definitely not a solution to describe the launcher as "dumb" or otherwise (https://github.com/gorilla-devs/GDLauncher/issues/1554 https://github.com/gorilla-devs/GDLauncher/issues/1555). With this you disrespect all the people that have done work on this project and violate the [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines).

### Additional reasoning taken into account
This is not your first comment done in a disrespectful way. Mainly I found https://github.com/Funwayguy/OreExcavation/issues/93.

Usage of caps lock instead of markdown **formatting**. Although this may be a personal preference and wouldn't even receive a note without excessive use this, together with the missing issue form (four times, three even after advisement) and the requested "[position] in the file directory" for the resolution parameters, this suggests missing knowledge about this project or more likely about the platform.

I also see you can leave much friendlier messages if you want (mainly in https://github.com/ricksouth/serilum-mc-mods/). I encourage you to keep that motivation!

### Answers
> Please tell me where the resolution parameters are in the file directory

To my knowledge, there is no such file to set the resolution set in the code for an electron app. And even if you could find it, these minimum size restrictions wouldn't help you much on this app, as much of the css is designed only to these margins. I've tried making the boundaries smaller before, and it breaks stuff like the instances grid, the Minecraft news ticker and most of the modals at smaller sizes. **This boundary is there or a reason.**

> This shouldn't be a complicated thing to fix.

As described above, this is actually a bit more complicated than just changing the minimum boundaries. It requires many css changes all around the project. Also, as this is an open source project, I always encourage anyone to just go and just **fix it yourself**. This project, although nearly unmaintained atm, still happily accepts pull requests. More about that in the following.

### State of the project
Currently, most of our organization is working on the rewrite of this whole app in another programming language, leaving basically only me to do the minimal maintenance on this *near-legacy* launcher. I do what I can, but I won't go and fix many bugs or even introduce new features myself. I still feel responsible against anyone else that creates a pr to review it and, if possible, merge it. The same counts for this issue tracker: I do all work necessary to keep it running by closing duplicates, labeling issues and generally moderating it.

Additionally, this is a open source project. I myself am a volunteer working on the code and also as moderator on this issue tracker in my free time. This is also the case for many other contributors to this project. All this work has been done voluntary and correspondingly the work gets affected by any personal preferences or life.

**Closed as not planned by Eskaan** 2023-03-07 06:32 UTC
Labels: Invalid
