### ISSUE TITLE
Curse Forge not loading

### ISSUE THREAD

**Issue by skyeblueocean** [killpowa/Twickt-Launcher#1358] opened 2022-06-11 23:41 UTC
![image](https://user-images.githubusercontent.com/59319871/173208357-e5317f09-2f76-48d1-a2d8-c025d035d89a.png)

**Comment by Jay420blaze** [comment] 2022-06-12 12:24
same here

**Comment by CanBoy67** [comment] 2022-06-12 17:09
That will fix by updating the launcher like I did, however due to the api issues while the mods will load they aren't guaranteed to download. Because curseforge is attempting to force all of us to use there over bloated launcher to play modded minecraft

**Comment by skyeblueocean** [comment] 2022-06-12 21:09
> That will fix by updating the launcher like I did, however due to the api issues while the mods will load they aren't guaranteed to download. Because curseforge is attempting to force all of us to use there over bloated launcher to play modded minecraft

I have the most recent version of the launcher, it still does not work

**Comment by Shadownite64** [comment] 2022-06-13 14:28
Their bloated launcher dont even work, still cant play 1.19 modded even with it.

**Comment by Jay420blaze** [comment] 2022-06-13 15:12
Been able to use the latest release on github without much problem, says the curseforge API is glitchy but haven't had any issues yet, have u guys tried downloading and installing that?

**Comment by Eskaan** [comment] 2022-06-13 18:14
Duplicate of #1342

**Closed as not planned** 2022-06-13 18:15 UTC

**Comment by Eskaan** [comment] 2022-06-13 18:20
Actually not, ist already fixed in the latest release (v1.1.23)
