### ISSUE TITLE
I can't update my launcher on Steam Deck

### ISSUE THREAD

**Issue by V1ENT0** [killpowa/Twickt-Launcher#1543] opened 2023-02-08 08:16 UTC
The problem is that it is not possible to open the appImage that can be downloaded from the site on steam OS.  

The Auto Updates not working says not available.  The only thing I can download is the version that is in the Discover application, but it is still version 1.1.29, and as I wrote, it cannot be updated.  

So in this case, I would like to ask for help, because nothing works, I try everything I can.

Thank you in advance for your help.

**Comment by Eskaan** [comment] 2023-02-08 08:31
Duplicate of #1528

**Closed as not planned** 2023-02-08 08:31 UTC
